In [7]:
import pandas as pd
import pandas_datareader.data as web
import datetime as dt
import matplotlib.pyplot as plt
import numpy as np

In [8]:
stocks = ['GOOG', 'IBM', 'AAPL', 'SPY']

start = dt.datetime(1970,1,1)
end = dt.datetime(2019,12,31)

df = pd.DataFrame()

for stock in stocks:
    
    df[stock] = web.DataReader(stock, 'yahoo', start, end)['Adj Close']

df.head() 

GOOG        IBM      AAPL        SPY
Date                                                 
2004-08-19  49.982655  55.556698  1.895552  79.441208
2004-08-20  53.952770  55.792255  1.901106  79.998734
2004-08-23  54.495735  55.399601  1.918389  79.795982
2004-08-24  52.239193  55.438900  1.972090  79.904640
2004-08-25  52.802086  55.674500  2.039986  80.447693

In [9]:
nd1 = df.values
nd1[0,0]

49.9826545715332

In [10]:
np.array([1,2,3])

array([1, 2, 3])

In [12]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.empty([5,4]) # initial values are garbages

array([[8.45590538e-307, 9.34609111e-307, 9.34593493e-307,
        1.33511562e-306],
       [1.69119330e-306, 1.42419802e-306, 1.78020169e-306,
        6.23053954e-307],
       [2.22522597e-306, 1.33511969e-306, 1.37962320e-306,
        9.34604358e-307],
       [9.79101082e-307, 1.78020576e-306, 1.69119873e-306,
        2.22522868e-306],
       [1.24611809e-306, 8.06632139e-308, 1.60221208e-306,
        2.29178686e-312]])

In [14]:
np.ones([5,4]) # 1 in float type

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.ones([5,4], dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [16]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.zeros([5,4], dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
np.random.random([5,4])

array([[0.75333161, 0.25470237, 0.06547063, 0.69765995],
       [0.34350498, 0.54004038, 0.81077388, 0.99199443],
       [0.26909369, 0.76748951, 0.55186545, 0.69527298],
       [0.48257375, 0.14416797, 0.87761203, 0.35849364],
       [0.70465601, 0.41569621, 0.2142297 , 0.50383022]])

In [19]:
np.random.rand(5,4)

array([[0.57274232, 0.46102776, 0.00740551, 0.68878336],
       [0.42469014, 0.31869862, 0.83229682, 0.73214004],
       [0.65201758, 0.88293366, 0.63159689, 0.19729781],
       [0.95293164, 0.47950923, 0.96027842, 0.08307419],
       [0.45535534, 0.54611687, 0.33243598, 0.79605313]])

In [20]:
np.random.normal(size=[2,3])

array([[ 0.57546964, -0.69286176,  0.24690796],
       [ 0.7397322 ,  0.64614372,  1.8415994 ]])

In [21]:
np.random.normal(50,10,size=[2,3])

array([[53.42349589, 49.27720253, 44.59617204],
       [68.69343083, 62.86529058, 48.38021758]])